# Generated by Django 4.2.5 on 2023-09-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_description', '0003_drug_medicine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='active',
            new_name='is_active',
        ),
    ]
